config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :subscriptions, :only => [:new, :create, :delete]
  resources :picnics
  resources :invites
  resources :photo_galleries
  resources :contacts, :only => [:new, :create]
  
  root 'static_pages#home'
  
  get 'static_pages/contact'
  get 'static_pages/why_picnics'
  get 'static_pages/what_to_bring'
  get 'static_pages/home'
  get 'about' => 'static_pages#about'
    
  get 'photos/show'
  get 'photos/create'
  
  get 'invite/create'
  get 'contact' => 'contacts#new'
  get '/calendar' => 'calendar#calendar'

  post 'subscriptions/subscribe' => 'subscriptions#subscribe'

  

end

app/models/picnic.rb
class Picnic < ActiveRecord::Base
  
  mount_uploader :image, ImageUploader
    
  belongs_to :host, :class_name => "User"
  has_many :invites, dependent: :destroy
  has_many :users, through: :invites
  has_one :photo_gallery
  has_many :photos, through: :photo_gallery
  before_save :set_just_date
  after_create :create_photo_gallery
  
  
  accepts_nested_attributes_for :invites
  scope :future_picnics, -> { where('date >= ?', Date.today).order(:date) }
  scope :past_picnics, -> { where('date <= ?', Date.today).order(:date).reverse }
  

  private

    def set_just_date
      self.just_date = self.date.to_date
    end
  
end

app/controllers/picnics_controller.rb
class PicnicsController < ApplicationController
  before_action :set_picnic, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :ensure_admin!, :except => [:show, :index]

  respond_to :html

  def index
    @picnics = Picnic.all
    future_picnics = Picnic.future_picnics
    @next_picnic = future_picnics.first
    @future_picnics = future_picnics[1..100]
    @past_picnics = Picnic.past_picnics.first(4)
    respond_with(@picnics)
  end

  def show
    @picnic = Picnic.find(params[:id])
    @invites = @picnic.invites.eager_load(:user)
    @invite = current_user.invites.build(picnic_id: @picnic.id) if user_signed_in?
    @users = @picnic.users
  end

  def new
    @picnic = current_user.hosted_picnics.new
    respond_with(@picnic)
  end

  def edit
  end

  def create
    @picnic = current_user.hosted_picnics.build(picnic_params)
    if @picnic.save
      redirect_to @picnic
    else
      format.html { render :new }
    end 
  end

  def update
    @picnic.update(picnic_params)
    respond_with(@picnic)
  end

  def destroy
    @picnic.destroy
    respond_with(@picnic)
  end

  private
    def set_picnic
      @picnic = Picnic.find(params[:id])
    end
    
    def picnic_params
      params.require(:picnic).permit(:name, :date, :description, :image)
    end

    
    
end

app/helpers/picnics_helper.rb
module PicnicsHelper
end

app/views/picnics/_form.html.erb
<%= form_for @picnic, :html => {:multipart => true} do |f| %>
  <% if @picnic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picnic.errors.count, "error") %> prohibited this picnic from being saved:</h2>

      <ul>
      <% @picnic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %></br>
  <%= f.text_field :name, class: "form-field" %></br>
  
  <%= f.label :date %></br>
  <%= f.datetime_select :date %></br>
  
  
  <%= f.label :description %></br>
  <%= f.text_area :description, class: "form-field" %></br>

  <%= f.label :image %></br>
  <%= f.file_field :image %></br>

  <div class="actions">
    <%= f.submit "Submit", class: "perfect-red-button" %>
  </div>
<% end %>

app/views/picnics/_form.html.haml
= form_for @picnic, :html => {:multipart => true} do |f|
  - if @picnic.errors.any?
    #error_explanation
      %h2
        = pluralize(@picnic.errors.count, "error")
        prohibited this picnic from being saved:
      %ul
        - @picnic.errors.full_messages.each do |message|
          %li= message
  = f.label :name
  = f.text_field :name, class: "form-field"
  = f.label :date
  = f.datetime_select :date
  = f.label :description
  = f.text_area :description, class: "form-field"
  = f.label :image
  = f.file_field :image
  .actions
    = f.submit "Submit", class: "perfect-red-button"

app/views/picnics/edit.html.erb
<div class="container">

<h1>Editing picnic</h1>

<%= render 'form' %>

<%= link_to 'Show', @picnic %> |
<%= link_to 'Back', picnics_path %>
</div>

app/views/picnics/edit.html.haml
.container
  %h1 Editing picnic
  = render 'form'
  = link_to 'Show', @picnic
  |
  = link_to 'Back', picnics_path

app/views/picnics/index.html.erb
<%= image_tag "picnic_food.jpg", class: "stretchimage" %>

<div class="container">
<% if @next_picnic %>
  <h1 class="next_picnic">Next Picnic</h1>
  <hr class="h_rule">  
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 center">
      <div class="three_cols">
        <h2><%= link_to @next_picnic.name, picnic_path(@next_picnic) %></h2>
      </div>
      <%= link_to image_url(picnic_path(@next_picnic)) do %>
        <%= image_tag @next_picnic.image, width: "400" %>
      <% end %>
      <p class="about_description"><%= @next_picnic.description %></p>
      <h2>The picnic is happening in <%= distance_of_time_in_words_to_now(@next_picnic.date) %>.</h2>
      <%= link_to "RSVP", picnic_path(@next_picnic), class: "btn perfect-red-button" %>
  </div>
<hr class="h_rule">
</div> 

<h1 class="next_picnic">Upcoming Picnics</h1>
<hr class="h_rule"> 
<div class="row">
  <% @future_picnics.in_groups_of(2, false) do |picnics| %>
    <% picnics.each do |picnic| %>
      <div class="col-sm-6 center">
        <div class="three_cols">
          <h3><%= link_to picnic.name, picnic_path(picnic) %></h3>
        </div>        
        <%= link_to image_url(picnic_path(picnic)) do %>
            <%= image_tag picnic.image, width: "300" %>
          <% end %>
        <div class="short_description">
          <%= simple_format(truncate(picnic.description, length: 200)) %>
        </div>
        <h4 class="center date"><%= (picnic.date.strftime("%A, %B %d, %Y at %l:%M %p")) %></h4>
        <%= link_to "RSVP", picnic_path(picnic), class: "btn perfect-red-button" %>
      </div>
    <% end %>
  <% end %>
</div>
<hr class="h_rule">
<% else %>
  
  <h1 class="next_picnic">Next Picnic</h1>
  <hr class="h_rule">  
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <p>There are no upcoming picnics currently scheduled. Enter your email below
      and we'll email you about the next one.</p>
     <div class="center">    
      <%= form_for Subscription.new do |f| %>
         <%= f.text_field :email, :placeholder => "enter email", class: "subscribe-field"%>
         <%= f.submit "Go", class: "subscribe-button" %>
      <% end %>
      </div>
    </div>
  </div>
<% end %>
<h1 class="next_picnic">Past Picnics</h1>
<hr class="h_rule">  
<div class="row">
  <% @past_picnics.in_groups_of(2,false) do |picnics| %>
    <div class="row">
      <% picnics.each do |picnic| %>
        <div class="col-sm-6 center">
          <div class="three_cols">
            <h3><%= link_to picnic.name, picnic_path(picnic) %></h3>
          </div>
          <%= link_to image_url(picnic_path(picnic)) do %>
            <%= image_tag picnic.image, width: "300" %>
          <% end %>
          <div class="short_description">
            <%= simple_format(truncate(picnic.description, length: 200)) %>
          </div>  
          <h4 class="center date"><%= (picnic.date.strftime("%A, %B %d, %Y at %l:%M %p")) %></h4>
          </div>
      <% end %>
    </div>
  <% end %>
</div>
    <hr class="h_rule">
</div>

app/views/picnics/index.html.haml
= image_tag "picnic_food.jpg", class: "stretchimage"
.container
  - if @next_picnic
    %h1.next_picnic Next Picnic
    %hr.h_rule/
    .row
      .col-sm-8.col-sm-offset-2.center
        .three_cols
          %h2= link_to @next_picnic.name, picnic_path(@next_picnic)
        = image_tag @next_picnic.image, width: "400"
        %p.about_description= @next_picnic.description
        %h2
          The picnic is happening in #{distance_of_time_in_words_to_now(@next_picnic.date)}.
        = link_to "RSVP", picnic_path(@next_picnic), class: "btn perfect-red-button"
      %hr.h_rule/
    %h1.next_picnic Upcoming Picnics
    %hr.h_rule/
    .row
      - @future_picnics.in_groups_of(2, false) do |picnics|
        - picnics.each do |picnic|
          .col-sm-6.center
            .three_cols
              %h3= link_to picnic.name, picnic_path(picnic)
            = image_tag picnic.image, width: "300"
            .short_description
              = simple_format(truncate(picnic.description, length: 200))
            %h4.center.date= (picnic.date.strftime("%A, %B %d, %Y at %l:%M %p"))
            = link_to "RSVP", picnic_path(picnic), class: "btn perfect-red-button"
    %hr.h_rule/
  - else
    %h1.next_picnic Next Picnic
    %hr.h_rule/
    .row
      .col-md-6.col-md-offset-3
        %p
          There are no upcoming picnics currently scheduled. Enter your email below
          and we'll email you about the next one.
        .center
          = form_for Subscription.new do |f|
            = f.text_field :email, :placeholder => "enter email", class: "subscribe-field"
            = f.submit "Go", class: "subscribe-button"
  %h1.next_picnic Past Picnics
  %hr.h_rule/
  .row
    - @past_picnics.in_groups_of(2,false) do |picnics|
      .row
        - picnics.each do |picnic|
          .col-sm-6.center
            .three_cols
              %h3= link_to picnic.name, picnic_path(picnic)
            = image_tag picnic.image, width: "300"
            .short_description
              = simple_format(truncate(picnic.description, length: 200))
            %h4.center.date= (picnic.date.strftime("%A, %B %d, %Y at %l:%M %p"))
  %hr.h_rule/

app/views/picnics/new.html.erb
<div class="container">
<h1>New picnic</h1>

<%= render 'form' %>

<%= link_to 'Back', picnics_path %>
</div>

app/views/picnics/new.html.haml
.container
  %h1 New picnic
  = render 'form'
  = link_to 'Back', picnics_path

app/views/picnics/show.html.erb
 <div class="picnic">
   <div class="picnic_img">
     <%= image_tag "picnic.jpg" %>
   </div>

<div class="container">
 
    <p id="notice"><%= notice %></p>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h1><%= @picnic.name %></h1>
        <hr class="h_rule">
        <h3 class="center date"><%= (@picnic.date.strftime("%A, %B %d, %Y at %l:%M %p")) %></h3>
      
       <!--<div class="show-picnic-img">-->
         <%#= image_tag @picnic.image, width: "400" %>
       <!--</div>  -->
        <%= image_tag @picnic.image, :id => 'myImg', alt: @picnic.name %>
        <div id="photoModal" class="modal">
          <img class="modal-content" id="img01">
          <div id="caption"></div>
        </div>
        
       <div class="fb-like" data-href= <%= picnic_path(@picnic) %> data-width="100" 
       data-layout="standard" data-action="like" data-show-faces="false" data-share="true">
       </div>
       <p><%= simple_format @picnic.description, class: "description" %></p>
       <p class="host">This Picnic is hosted by: <strong><%= @picnic.host.first_name %></strong></p>
      </div>
    </div>
  
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
         <% if user_signed_in? && @picnic.users.include?(current_user) %>
           <h3>Thanks for your RSVP. Looking forward to seeing you!</h3>
        <% elsif user_signed_in? %>
          <%= render 'shared/invite_form.html.erb' %>
        <% else %>
          <p> <%= link_to "Log in", new_user_session_path %> to RSVP.</p>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="rsvp">
          <h3>Guests: </h3>
   
          <% @picnic.users.each do |u|  %>
            <p><%= u.first_name %> is bringing <%= u.invites.find_by(picnic_id: @picnic.id).food %>.
            <% if u == current_user %>
              <%= link_to 'Change', edit_invite_path(u.invites.find_by(picnic_id: @picnic.id)) %>
            <% end %> 
            </p>
          <% end %> 
        </div>
          <% if current_user == @picnic.host %>
            <%= link_to 'Edit Picnic Info', edit_picnic_path(@picnic) %> 
            <%= link_to 'Cancel Picnic', picnic_path(@picnic),  method: :delete, 
              data: {confirm: 'Are you sure?' } %> 
          <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  var modal = document.getElementById('photoModal');
  var flag = false;
  
  $('#photoModal').bind('touchstart click', function(event){
    if (!flag) {
      flag = true;
      setTimeout(function(){ flag = false; }, 100);
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
    return false
  });
  
  // Get the image and insert it inside the modal - use its "alt" text as a caption
  var img = document.getElementById('myImg');
  var modalImg = document.getElementById("img01");
  var captionText = document.getElementById("caption");
  img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
    captionText.innerHTML = this.alt;
  }
</script>

app/views/picnics/show.html.haml
.picnic
  .picnic_img
    = image_tag "picnic.jpg"
  .container
    %p#notice= notice
    .row
      .col-sm-6.col-sm-offset-3
        %h1= @picnic.name
        %hr.h_rule/
        %h3.center.date= (@picnic.date.strftime("%A, %B %d, %Y at %l:%M %p"))
        .show-picnic-img
          = image_tag @picnic.image, width: "400"
        .fb-like{"data-href" => "<haml_loud"}
          picnic_path(@picnic)  data-width="100"
          data-layout="standard" data-action="like" data-show-faces="false" data-share="true"&gt;
        %p= simple_format @picnic.description, class: "description"
        %p.host
          This Picnic is hosted by:
          %strong= @picnic.host.first_name
    .row
      .col-sm-6.col-sm-offset-3
        - if user_signed_in? && @picnic.users.include?(current_user)
          %h3 Thanks for your RSVP. Looking forward to seeing you!
        - elsif user_signed_in?
          = render 'shared/invite_form.html.erb'
        - else
          %p
            = link_to "Log in", new_user_session_path
            to RSVP.
    .row
      .col-sm-6.col-sm-offset-3
        .rsvp
          %h3 Guests:
          - @picnic.users.each do |u|
            %p
              = u.first_name
              is bringing #{u.invites.find_by(picnic_id: @picnic.id).food}.
              - if u == current_user
                = link_to 'Change', edit_invite_path(u.invites.find_by(picnic_id: @picnic.id))
        - if current_user == @picnic.host
          = link_to 'Edit Picnic Info', edit_picnic_path(@picnic)
          = link_to 'Cancel Picnic', picnic_path(@picnic),  method: :delete, |
            data: {confirm: 'Are you sure?' }                                |