config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :subscriptions, :only => [:new, :create, :delete]
  resources :picnics
  resources :invites
  resources :photo_galleries
  resources :contacts, :only => [:new, :create]
  
  root 'static_pages#home'
  
  get 'static_pages/contact'
  get 'static_pages/why_picnics'
  get 'static_pages/what_to_bring'
  get 'static_pages/home'
  get 'about' => 'static_pages#about'
    
  get 'photos/show'
  get 'photos/create'
  
  get 'invite/create'
  get 'contact' => 'contacts#new'
  get '/calendar' => 'calendar#calendar'

  post 'subscriptions/subscribe' => 'subscriptions#subscribe'

  

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
    
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

    def new 
    end 
    
    def show
      @subscription = Subscription.find(params[:id])
    end 
    
    def edit
        @subscription = Subscription.find(params[:id])
    end 
    
    def create
        @subscription = Subscription.new(subscription_params)
        if @subscription.save
            flash[:notice] = "Thank you! We'll email you about the next picnic."
            SubscriptionMailer.welcome_email(@subscription).deliver!
            redirect_to root_path
        else
           flash[:alert] = "Email address is not valid. Please enter a valid email."
           redirect_to root_path
        end
    end 
    
    def update
      @subscription = Subscription.find(params[:id])    
      @subscription.update(subscription_params)
      flash[:notice] = "Thanks for updating your email."
      redirect_to root_path
    end 
    
    def destroy
        @subscription = Subscription.find(params[:id])
        @subscription.destroy
        flash[:notice] = "You've unsubscribed. Check back for upcoming picnics."
        redirect_to root_url
    end 
    private
        def subscription_params
            params.require(:subscription).permit(:email)
        end 

end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/subscriptions/edit.html.erb
<div class="container">
  <div class="col-md-4 col-md-offset-4">

<h1>Change Subscription</h1>

<%= form_for @subscription, :html => {:multipart => true} do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this picnic from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :email %></br>
  <%= f.text_field :email, class: "form-field" %></br>
  
  <div class="actions">
    <%= f.submit "Submit", class: "perfect-red-button" %>
  </div>
<% end %>


<%= link_to 'Unsubscribe', subscription_path(@subscription),  method: :delete, 
              data: {confirm: 'Are you sure?' } %> 

  </div>
</div>  

app/views/subscriptions/edit.html.haml
.container
  .col-md-4.col-md-offset-4
    %h1 Change Subscription
    = form_for @subscription, :html => {:multipart => true} do |f|
      - if @subscription.errors.any?
        #error_explanation
          %h2
            = pluralize(@subscription.errors.count, "error")
            prohibited this picnic from being saved:
          %ul
            - @subscription.errors.full_messages.each do |message|
              %li= message
      = f.label :email
      = f.text_field :email, class: "form-field"
      .actions
        = f.submit "Submit", class: "perfect-red-button"
    = link_to 'Unsubscribe', subscription_path(@subscription),  method: :delete, |
      data: {confirm: 'Are you sure?' }                                          |

app/views/subscriptions/show.html.erb
<div class="container">
  <div class="col-md-4 col-md-offset-4">

<h1>Change Subscription</h1>

<%= form_for @subscription, :html => {:multipart => true} do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this picnic from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <%= f.label :email %></br>
  <%= f.text_field :email, class: "form-field" %></br>
  
  <div class="actions">
    <%= f.submit "Submit", class: "perfect-red-button" %>
  </div>
<% end %>


<%= link_to 'Unsubscribe', subscription_path(@subscription),  method: :delete, 
              data: {confirm: 'Are you sure?' } %> 

  </div>
</div>  

app/views/subscriptions/show.html.haml
.container
  .col-md-4.col-md-offset-4
    %h1 Change Subscription
    = form_for @subscription, :html => {:multipart => true} do |f|
      - if @subscription.errors.any?
        #error_explanation
          %h2
            = pluralize(@subscription.errors.count, "error")
            prohibited this picnic from being saved:
          %ul
            - @subscription.errors.full_messages.each do |message|
              %li= message
      = f.label :email
      = f.text_field :email, class: "form-field"
      .actions
        = f.submit "Submit", class: "perfect-red-button"
    = link_to 'Unsubscribe', subscription_path(@subscription),  method: :delete, |
      data: {confirm: 'Are you sure?' }                                          |