config/routes.rb
Rails.application.routes.draw do
  devise_for :users,  :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :subscriptions, :only => [:new, :create, :delete]
  resources :picnics
  resources :invites
  resources :photo_galleries
  resources :contacts, :only => [:new, :create]
  
  root 'static_pages#home'
  
  get 'static_pages/contact'
  get 'static_pages/why_picnics'
  get 'static_pages/what_to_bring'
  get 'static_pages/home'
  get 'about' => 'static_pages#about'
    
  get 'photos/show'
  get 'photos/create'
  
  get 'invite/create'
  get 'contact' => 'contacts#new'
  get '/calendar' => 'calendar#calendar'

  post 'subscriptions/subscribe' => 'subscriptions#subscribe'

  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :user
  belongs_to :picnic
end

app/models/photo.rb
class Photo < ActiveRecord::Base
    

    mount_uploader :image, ImageUploader
    belongs_to :photo_gallery
    has_one :picnic, through: :photo_gallery
end

app/models/photo_gallery.rb
class PhotoGallery < ActiveRecord::Base
    
    
    belongs_to :picnic
    has_many :photos
    
  
    
end

app/models/picnic.rb
class Picnic < ActiveRecord::Base
  
  mount_uploader :image, ImageUploader
    
  belongs_to :host, :class_name => "User"
  has_many :invites, dependent: :destroy
  has_many :users, through: :invites
  has_one :photo_gallery
  has_many :photos, through: :photo_gallery
  before_save :set_just_date
  after_create :create_photo_gallery
  
  
  accepts_nested_attributes_for :invites
  scope :future_picnics, -> { where('date >= ?', Date.today).order(:date) }
  scope :past_picnics, -> { where('date <= ?', Date.today).order(:date).reverse }
  

  private

    def set_just_date
      self.just_date = self.date.to_date
    end
  
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
    
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  
  devise :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :hosted_picnics, :foreign_key => "host_id", :class_name => "Picnic"       
  has_many :invites, :foreign_key => "user_id", :class_name => "Invite"
  has_many :picnics, through: :invites
  
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
  
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
    
    def calendar 
        @date = params[:date] ? Date.parse(params[:date]) : Date.today
        @picnics = Picnic.all 
        @picnics_by_date = @picnics.group_by(&:just_date)
    end 
    
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :set_invite, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @invites = Invite.all
    respond_with(@invites)
  end

  def show
  @invite = Invite.find(params[:id])
    respond_with(@invite)
  end

  def new
    @invite = Invite.new
    respond_with(@invite)
  end

  def edit
    @invite = Invite.find(params[:id])
    @picnic = Picnic.find(@invite.picnic_id)
  end

  def create
    @invite = Invite.new(invite_params)
    # @invite.picnic_id = @invite.picnic_id.to_i
    @invite.save
    # respond_with(@invite)
    redirect_to picnic_path(@invite.picnic_id)
  end

  def update
    @invite.update(invite_params)
    redirect_to picnic_path(@invite.picnic_id)
  end

  def destroy
    @invite.destroy
    respond_with(@invite)
  end

  private
    def set_invite
      @invite = Invite.find(params[:id])
    end

    def invite_params
      params.require(:invite).permit(:picnic_id, :user_id, :food)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  
  def new
    @photo_gallery = PhotoGallery.find(params[:id])
    @photos = @photo_gallery.photos.build
  end 
  
  def show
  end

end

app/controllers/picnics_controller.rb
class PicnicsController < ApplicationController
  before_action :set_picnic, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :ensure_admin!, :except => [:show, :index]

  respond_to :html

  def index
    @picnics = Picnic.all
    future_picnics = Picnic.future_picnics
    @next_picnic = future_picnics.first
    @future_picnics = future_picnics[1..100]
    @past_picnics = Picnic.past_picnics.first(4)
    respond_with(@picnics)
  end

  def show
    @picnic = Picnic.find(params[:id])
    @invites = @picnic.invites.eager_load(:user)
    @invite = current_user.invites.build(picnic_id: @picnic.id) if user_signed_in?
    @users = @picnic.users
  end

  def new
    @picnic = current_user.hosted_picnics.new
    respond_with(@picnic)
  end

  def edit
  end

  def create
    @picnic = current_user.hosted_picnics.build(picnic_params)
    if @picnic.save
      redirect_to @picnic
    else
      format.html { render :new }
    end 
  end

  def update
    @picnic.update(picnic_params)
    respond_with(@picnic)
  end

  def destroy
    @picnic.destroy
    respond_with(@picnic)
  end

  private
    def set_picnic
      @picnic = Picnic.find(params[:id])
    end
    
    def picnic_params
      params.require(:picnic).permit(:name, :date, :description, :image)
    end

    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/invite_helper.rb
module InviteHelper
end

app/helpers/photo_galleries_helper.rb
module PhotoGalleriesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/picnics_helper.rb
module PicnicsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-2 first-col-footer">
                <h4 class="first-col-footer-title">
                    Picnic Info
                </h4>
               <h4 class="footer-link">
                    <a href="/about">About ThePicnic.nyc</a>
                </h4>
                <h4 class="footer-link">
                  <a href="#" class="footer-link">What should I bring?</a><br>    
                </h4>
            </div>
            <div class="col-sm-2 second-col-footer">
                <h4>
                    <a href="#">Host a Picnic</a>
                </h4>
                <h4>
                    <%= link_to "Photos", photo_galleries_path %>
                </h4>
                <h4>
                    <a href="/contact">Contact</a>
                </h4>
                <h4>
                    <%= link_to "Calendar", calendar_path %>
                </h4>
            </div>
            <div class="col-sm-5 subscription">
              <h4>
                  Subscribe for updates:
              </h4 class="subscription-form">
              <%= render 'shared/subscription_form' %>
              <h4>
                  Still not convinced?
              </h4>
              <p class="pitch">
                  We have tons of fun at our picinics and there are pictures 
                  to prove it. Check them out <%= link_to 'here', photo_galleries_path %>.
              </p>
            </div>
            <div class="col-sm-3">
                
                <% if user_signed_in? %>
                <h4>
                    <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
                </h4>
                <h4>
                    <%= link_to "Settings", edit_user_registration_path %>
                </h4>
                <% else %>
                <h4>
                    <%= link_to "Login", new_user_session_path %>
                </h4>
                <h4>
                    <%= link_to "Create Account", new_user_registration_path %>
                </h4>
                <% end %>
                <ul>
                    <li>
                        <%= image_tag("twitter.png") %> 
                    </li>
                    <li>
                        <%= image_tag("facebook.png") %>
                    </li>
                    <li>
                        <%= image_tag("instagram.png") %>
                    </li>
                </ul>
            </div>
        </div>
    </div>    
</footer>

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .col-sm-2.first-col-footer
        %h4.first-col-footer-title
          Picnic Info
        %h4.footer-link
          %a{:href => "/about"} About ThePicnic.nyc
        %h4.footer-link
          %a.footer-link{:href => "#"} What should I bring?
          %br/
      .col-sm-2.second-col-footer
        %h4
          %a{:href => "#"} Host a Picnic
        %h4
          = link_to "Photos", photo_galleries_path
        %h4
          %a{:href => "/contact"} Contact
        %h4
          = link_to "Calendar", calendar_path
      .col-sm-5.subscription
        %h4
          Subscribe for updates:
        = render 'shared/subscription_form'
        %h4
          Still not convinced?
        %p.pitch
          We have tons of fun at our picinics and there are pictures
          to prove it. Check them out #{link_to 'here', photo_galleries_path}.
      .col-sm-3
        - if user_signed_in?
          %h4
            = link_to 'Log out', destroy_user_session_path, method: :delete
          %h4
            = link_to "Settings", edit_user_registration_path
        - else
          %h4
            = link_to "Login", new_user_session_path
          %h4
            = link_to "Create Account", new_user_registration_path
        %ul
          %li
            = image_tag("twitter.png")
          %li
            = image_tag("facebook.png")
          %li
            = image_tag("instagram.png")

app/views/layouts/_navbar.html.erb
<div class="masthead">
    <div class="container">
        <div class="row">
            <h1>
                <%= link_to 'ThePicnic.nyc', root_path %>
            </h1>
        </div>
    </div>
</div>
<div id="nav" class="affix-top">
    <div class="navbar navbar-default navbar-static">
        <div class="container">
            <div class="navbar-header">
                <button type="button" data-toggle="collapse" data-target=".navbar-collapse" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav">
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Picnics", picnics_path %></li>
                    <li><%= link_to "Photos", photo_galleries_path %></li>
                    <li><%= link_to "Contact Us", contact_path %></li>
                    <% if user_signed_in? %>
                        <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                    <% else %>
                        <li><%= link_to "Login", new_user_session_path %></li>
                    <!--<li><%= link_to "Create Account", user_registration_path %></li>-->
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.haml
.masthead
  .container
    .row
      %h1
        = link_to 'ThePicnic.nyc', root_path
#nav.affix-top
  .navbar.navbar-default.navbar-static
    .container
      .navbar-header
        %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
      .collapse.navbar-collapse
        %ul.nav
          %li= link_to "Home", root_path
          %li= link_to "Picnics", picnics_path
          %li= link_to "Photos", photo_galleries_path
          %li= link_to "Contact Us", contact_path
          - if user_signed_in?
            %li= link_to 'Log out', destroy_user_session_path, method: :delete
          - else
            %li= link_to "Login", new_user_session_path
            / <li><haml_loud> link_to &quot;Create Account&quot;, user_registration_path </haml_loud></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThePicnic.nyc</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Fjalla+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>

</head>
<body ng-app="AngularPicnic">

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '109400096062882',
      xfbml      : true,
      version    : 'v2.3'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<%= render 'layouts/navbar' %>

<div class="container">
  <h3 class="notice"><%= notice %></h3>
  <h3 class="alert"><%= alert %></h3>
</div>

<%= yield %>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ThePicnic.nyc
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag    'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    // %link{:href => "https://fonts.googleapis.com/css?family=Fjalla+One", :rel => "stylesheet", :type => "text/css"}/
    // %link{:href => "http://fonts.googleapis.com/css?family=Arvo", :rel => "stylesheet", :type => "text/css"}/
    // %link{:href => "http://fonts.googleapis.com/css?family=Josefin+Sans", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Fjalla+One"
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Arvo"
    = stylesheet_link_tag "//fonts.googleapis.com/css?family=Josefin+Sans"
  
  %body{"ng-app" => "AngularPicnic"}
    :javascript
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '109400096062882',
          xfbml      : true,
          version    : 'v2.3'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
    = render 'layouts/navbar'
    .container
      %h3.notice= notice
      %h3.alert= alert
    = yield
    = render 'layouts/footer'

app/views/shared/_invite_form.html.erb
 <h2> RSVP </h2>
 
 <%= form_for @invite, :url => { :action => 'create', :controller => "invites"} do |f| %>
 <div class="actions">
  <p>Yes I will be coming and I am bringing:</p> 

    <%= f.text_field :food, autofocus: true, class: "form-field" %></br>

  
  <%= f.hidden_field  :picnic_id %>
  <%= f.hidden_field :user_id %>
    <%= f.submit "RSVP", class: "perfect-red-button" %>
  </div>
<% end %>

app/views/shared/_invite_form.html.haml
%h2 RSVP
= form_for @invite, :url => { :action => 'create', :controller => "invites"} do |f|
  .actions
    %p Yes I will be coming and I am bringing:
    = f.text_field :food, autofocus: true, class: "form-field"
    = f.hidden_field  :picnic_id
    = f.hidden_field :user_id
    = f.submit "RSVP", class: "perfect-red-button"

app/views/shared/_photos_form.html.erb
<%= form_for(@photo_gallery, :html => { :multipart => true }) do |f| %>
 
  <%= f.fields_for :photos do |p| %>

     <%= p.label :image %><br>
     <%= p.file_field :image, :multiple => true, name: "photos[image][]" %>
 
  <% end %>

 <%= f.submit "Upload photos", class: "subscribe-button" %>
<% end %>

app/views/shared/_photos_form.html.haml
= form_for(@photo_gallery, :html => { :multipart => true }) do |f|
  = f.fields_for :photos do |p|
    = p.label :image
    %br/
    = p.file_field :image, :multiple => true, name: "photos[image][]"
  = f.submit "Upload photos", class: "subscribe-button"

app/views/shared/_subscription_form.html.erb
<%= form_for Subscription.new do |f| %>
   <%= f.text_field :email, :placeholder => "enter email", class: "subscribe-field"%>
   <%= f.submit "Go", class: "subscribe-button" %>
<% end %>

app/views/shared/_subscription_form.html.haml
= form_for Subscription.new do |f|
  = f.text_field :email, :placeholder => "enter email", class: "subscribe-field"
  = f.submit "Go", class: "subscribe-button"